version: '2'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - workspace_network
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app/
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db/
  db:
    container_name: db
    image: postgres
    networks:
      - workspace_network
    environment:
      - POSTGRES_PASSWORD=password
networks:
  workspace_network:
    driver: bridge
